import { keeloConfig, logger } from '../../config/index.js';
import { createOctokitForInstallation } from './client.js';
import type { PullRequestContext } from '../../core/types.js';
import type { GeneratedTest } from '../../core/test-generator.js';
import type { CommitResult } from './git-operations.js';

// =============================================================================
// Types
// =============================================================================

export interface CreatedPullRequest {
  number: number;
  title: string;
  url: string;
  branch: string;
}

export interface CheckStatus {
  name: string;
  status: string;
  conclusion?: string;
  url?: string;
}

// =============================================================================
// PR Creation
// =============================================================================

export async function createTestPullRequest(
  context: PullRequestContext,
  commitResult: CommitResult,
  tests: GeneratedTest[],
  baseBranch: string
): Promise<CreatedPullRequest> {
  const octokit = createOctokitForInstallation(context.installationId);

  const prTitle = `🧪 [Keelo] Automated tests for PR #${context.pullNumber}`;
  
  const prBody = generatePRBody(context, tests, commitResult);

  const response = await octokit.pulls.create({
    owner: context.owner,
    repo: context.repo,
    title: prTitle,
    body: prBody,
    head: commitResult.branch,
    base: baseBranch,
    draft: keeloConfig.actions.createDraftPRs ?? true,
  });

  // Add labels
  try {
    await octokit.issues.addLabels({
      owner: context.owner,
      repo: context.repo,
      issue_number: response.data.number,
      labels: [...keeloConfig.actions.issueLabels, 'automated-tests'],
    });
  } catch (error) {
    logger.warn({ error }, 'Failed to add labels to PR');
  }

  // Link to original PR
  try {
    await octokit.issues.createComment({
      owner: context.owner,
      repo: context.repo,
      issue_number: context.pullNumber,
      body: `## 🧪 Automated Tests Generated

Keelo has created a PR with automated tests for this change:

**PR:** #${response.data.number}
**Branch:** \`${commitResult.branch}\`
**Tests:** ${tests.length} file(s)

| File | Framework | Type |
|------|-----------|------|
${tests.map(t => `| \`${t.filename}\` | ${t.framework} | ${t.type} |`).join('\n')}

---
*Review and merge the test PR to add these tests to your codebase.*`,
    });
  } catch (error) {
    logger.warn({ error }, 'Failed to comment on original PR');
  }

  logger.info({ 
    prNumber: response.data.number, 
    url: response.data.html_url 
  }, 'Test PR created successfully');

  return {
    number: response.data.number,
    title: prTitle,
    url: response.data.html_url,
    branch: commitResult.branch,
  };
}

function generatePRBody(
  context: PullRequestContext,
  tests: GeneratedTest[],
  commitResult: CommitResult
): string {
  const testsByType = tests.reduce((acc, t) => {
    acc[t.type] = (acc[t.type] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const testsByFramework = tests.reduce((acc, t) => {
    acc[t.framework] = (acc[t.framework] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return `## 🤖 Keelo - Automated Test Generation

This PR was automatically generated by **Keelo** based on the analysis of PR #${context.pullNumber}.

### 📋 Original PR
- **Title:** ${context.title}
- **PR:** #${context.pullNumber}

### 📊 Test Summary

| Metric | Value |
|--------|-------|
| Total Files | ${tests.length} |
| Commit | \`${commitResult.sha.substring(0, 7)}\` |

#### By Type
${Object.entries(testsByType).map(([type, count]) => `- **${type}:** ${count}`).join('\n')}

#### By Framework
${Object.entries(testsByFramework).map(([fw, count]) => `- **${fw}:** ${count}`).join('\n')}

### 📁 Files Added

${tests.map(t => `- \`${t.filename}\` (${t.framework} - ${t.type})`).join('\n')}

### 🔧 Dependencies

If any new dependencies are required:

\`\`\`bash
npm install -D ${[...new Set(tests.flatMap(t => t.dependencies))].join(' ')}
\`\`\`

### ✅ Checklist

- [ ] Review generated test code
- [ ] Verify test assertions are correct
- [ ] Run tests locally
- [ ] Merge if tests pass

---
*Generated by [Keelo](https://github.com/keelo) - Autonomous QA Agent*
`;
}

// =============================================================================
// PR Status Monitoring
// =============================================================================

export async function getPRChecksStatus(
  context: PullRequestContext,
  prNumber: number
): Promise<{ status: 'pending' | 'success' | 'failure'; checks: CheckStatus[] }> {
  const octokit = createOctokitForInstallation(context.installationId);

  // Get the PR to find the head SHA
  const pr = await octokit.pulls.get({
    owner: context.owner,
    repo: context.repo,
    pull_number: prNumber,
  });

  const headSha = pr.data.head.sha;

  // Get check runs
  const checkRuns = await octokit.checks.listForRef({
    owner: context.owner,
    repo: context.repo,
    ref: headSha,
  });

  const checks: CheckStatus[] = checkRuns.data.check_runs.map(run => ({
    name: run.name,
    status: run.status,
    conclusion: run.conclusion || undefined,
    url: run.html_url || undefined,
  }));

  // Determine overall status
  let status: 'pending' | 'success' | 'failure' = 'pending';
  
  if (checks.length > 0 && checks.every(c => c.status === 'completed')) {
    status = checks.every(c => c.conclusion === 'success') ? 'success' : 'failure';
  }

  return { status, checks };
}

// =============================================================================
// Failure Reporting
// =============================================================================

export async function reportCIFailures(
  context: PullRequestContext,
  prNumber: number,
  checks: CheckStatus[]
): Promise<void> {
  const octokit = createOctokitForInstallation(context.installationId);

  const failedChecks = checks.filter(c => c.conclusion === 'failure');
  
  if (failedChecks.length === 0) return;

  const comment = `## ❌ CI Failures Detected

The automated tests PR #${prNumber} has failing checks:

| Check | Status | Link |
|-------|--------|------|
${failedChecks.map(c => `| ${c.name} | ❌ Failed | ${c.url ? `[View](${c.url})` : 'N/A'} |`).join('\n')}

### Recommended Actions
1. Review the failing tests
2. Fix any issues in the test code
3. Re-run the CI pipeline

---
*Reported by [Keelo](https://github.com/keelo) - Autonomous QA Agent*
`;

  await octokit.issues.createComment({
    owner: context.owner,
    repo: context.repo,
    issue_number: context.pullNumber,
    body: comment,
  });

  // Create issues for persistent failures
  if (keeloConfig.actions.autoCreateIssues) {
    for (const check of failedChecks) {
      try {
        await octokit.issues.create({
          owner: context.owner,
          repo: context.repo,
          title: `[Keelo] CI Failure: ${check.name}`,
          body: `## CI Check Failed

**Check:** ${check.name}
**Related PR:** #${prNumber}
**Original PR:** #${context.pullNumber}
${check.url ? `**Details:** ${check.url}` : ''}

This issue was created because an automated test CI check failed.

---
*Created by [Keelo](https://github.com/keelo)*
`,
          labels: [...keeloConfig.actions.issueLabels, 'ci-failure'],
        });
      } catch (error) {
        logger.error({ error, check: check.name }, 'Failed to create CI failure issue');
      }
    }
  }

  logger.info({ failedCount: failedChecks.length }, 'CI failures reported');
}
